### ISSUE TITLE
can not find performance_logger.py in multi_target_self_organizing_pursuit Folder

### ISSUE THREAD

**Issue by Yuxin916** [LijunSun90/pursuitFSC2#1]
Hi, thank you for this amazing work.

in train_sop_mappo.py and train_sop_mappo_global_state.py, i failed to import PerformanceLogger. 

Thank you for your help!

**Comment by LijunSun90** [comment]
> Hi, thank you for this amazing work.
> 
> in train_sop_mappo.py and train_sop_mappo_global_state.py, i failed to import PerformanceLogger.
> 
> Thank you for your help!

Hi, thank you for your feedback and sorry for the missing files. They are added in the repository and the script train_sop_mappo.py is runnable now.

**Comment by Yuxin916** [comment]
Thank you!
