### ISSUE TITLE
Multi-agent search stops at the edge of the map

### ISSUE THREAD

**Issue by LZL-boy** [LijunSun90/pursuitFSC2#4]
When my agent searches or runs away, it hits the edge and can't run

**Comment by LijunSun90** [comment]
Hi, 
1. the (self-organizing search) environment is designed in this way. When an agent collides with an obstacle, e.g., a boundary, it will die in its location.
2. If you want a less restricted search environment where an agent will be penalised by reward if it collides with obstacles but will keep alive and continue the game, we recommend the Pursuit-Evasion-O environment of our new work in https://github.com/LijunSun90/MatrixWorld. If you want to compare with our algorithm, you can continue use the current repository, or our new environment. We will integrate our algorithm FSC2 in that new repository soon.
3. If there are other problems, you are welcome to contact us.
