### ISSUE TITLE
I wonder if this collision detection is equivalent to assigning all_agents_positions_matrix all values to 0

### ISSUE THREAD

**Issue by LZL-boy** [LijunSun90/pursuitFSC2#5]
collisions = [all_agents_positions_matrix[self.pursuer_layer.get_position(agent_id)[0], self.pursuer_layer.get_position(agent_id)[1]] - 1
                      for agent_id in range(self.n_pursuers)]

**Comment by LijunSun90** [comment]
Please refere to https://github.com/LijunSun90/pursuitFSC2/issues/6
