### ISSUE TITLE
I wonder if this collision detection is equivalent to assigning all_agents_positions_matrix all values to 0I wonder if this collision detection is equivalent to assigning all_agents_positions_matrix all values to 0

### ISSUE THREAD

**Issue by LZL-boy** [LijunSun90/pursuitFSC2#6]
collisions = [all_agents_positions_matrix[self.pursuer_layer.get_position(agent_id)[0],
                                                  self.pursuer_layer.get_position(agent_id)[1]] - 1
                      for agent_id in range(self.n_pursuers)]

in

def get_collision_reward(self):
        """
        Added in Version-SOP.
        """
        pursuer_position_matrix = self.pursuer_layer.get_state_matrix()

        if self.surround:
            # No collisions are allowed
            evader_position_matrix = self.evader_layer.get_state_matrix()
            all_agents_positions_matrix = pursuer_position_matrix + evader_position_matrix
        else:
            # Collisions with evaders are allowed, while that with other pursuers are prevented.
            all_agents_positions_matrix = pursuer_position_matrix

        collisions = [all_agents_positions_matrix[self.pursuer_layer.get_position(agent_id)[0],
                                                  self.pursuer_layer.get_position(agent_id)[1]] - 1
                      for agent_id in range(self.n_pursuers)]

        self.n_agents_collide_with_others_per_multiagent_step = np.count_nonzero(collisions)
        self.n_collision_events_per_multiagent_step = np.count_nonzero(np.maximum(all_agents_positions_matrix - 1, 0))

        collision_rewards = self.collision_reward * np.asarray(collisions)

        self.n_collision_with_obstacles = np.sum([pursuer.collide_with_obstacle for pursuer in self.pursuers])

        return collision_rewards

**Comment by LijunSun90** [comment]
The agent-agent collision is defined as that more than one agents exist in one position of the matrix (grid world). And the total number of collisions occur in one time step is the summation of all collisions in all positions.

**Comment by LijunSun90** [comment]
The agent-agent collision is defined as that more than one agents exist in one position of the matrix (grid world). And the total number of collisions occur in one time step is the summation of all collisions in all positions.
