### ISSUE TITLE
About sos maddpg training time

### ISSUE THREAD

**Issue by LZL-boy** [LijunSun90/pursuitFSC2#7]
When running the train_sos_maddpg.py file, after 500episodes the training time is 3 to 10 times more than before, do you have this problem

**Comment by LijunSun90** [comment]
You can refererence our experimental result https://github.com/LijunSun90/pursuitFSC2/blob/main/multi_target_self_organizing_search/results/sos_MADDPG/result_Time(s).png for MADDPG on SOS (self-organizing search).
From our records, our training time is relative stable.

**Comment by LijunSun90** [comment]
You can refererence our experimental result https://github.com/LijunSun90/pursuitFSC2/blob/main/multi_target_self_organizing_search/results/sos_MADDPG/result_Time(s).png for MADDPG on SOS (self-organizing search).
From our records, our training time is relative stable.
