### ISSUE TITLE
capture_rate ，It's always 0

### ISSUE THREAD

**Issue by LZL-boy** [LijunSun90/pursuitFSC2#9]
in train_sop_mappo.py，train_sop_ippo.py，train_sop_actor_critic.py，capture_rate ，It's always 0
![image](https://github.com/user-attachments/assets/177f3363-29fc-4f9d-b1ef-c24f62fc3b70)

**Comment by LZL-boy** [comment]
![image](https://github.com/user-attachments/assets/827e52fe-1014-4be8-87d8-69853b744b8f)

**Comment by LijunSun90** [comment]
Hi, thank you for your question and welcome discussion! I checked one experiment data of mine just now. The "capture_rate" for train_sop_mappo.py is not always 0. For example, in the experiment I checked, capture_rate starts to increase above 0 after the epoch=6400.

**Comment by LijunSun90** [comment]
Hi, thank you for your question and welcome discussion! I checked one experiment data of mine just now. The "capture_rate" for train_sop_mappo.py is not always 0. For example, in the experiment I checked, capture_rate starts to increase above 0 after the epoch=6400. It takes some time for MARL to learn the surrounding-based capture.

**Comment by LZL-boy** [comment]
Sorry, I've only run 7000 steps, can I ask you how many steps you have run and the catch rate has reached 100%

**Comment by LijunSun90** [comment]
> Sorry, I've only run 7000 steps, can I ask you how many steps you have run and the catch rate has reached 100%

It's fine. You can refer to Fig. 5 in the paper https://arxiv.org/abs/2206.12330. Generally, the performance varies with the swarm density.
